### ISSUE TITLE
Calculating of pixelOffset

### ISSUE THREAD

**Issue by AppWerft** [jeffbonnes/parmavision#2]
Hi Jeff,

this line confuses me:

```
var pixelOffset = Math.floor((internalBearing % 1) * screenWidth) + ((panels[0].width - screenWidth) / 2);
```

%1 is always 0  http://jsfiddle.net/7k26w9gf/

What do you make with this line?? 

Updated: I found it is the fract of number.

**Comment by jeffbonnes** [comment]
Most of the calcs are based on Trevor's book.  Have you seen it? http://www.amazon.com/Augmented-Reality-Appcelerator-Titanium-Starter/dp/1849693900
